apiVersion: v1
kind: ConfigMap
metadata:
  name: patterns-operator-config
  namespace: openshift-operators
data:
  gitops.catalogSource: {{ .Values.main.gitops.operatorSource }}
  gitops.channel: {{ .Values.main.gitops.channel }}
  gitea.chartName: {{ .Values.main.gitea.chartName }}
  gitea.helmRepoUrl: {{ .Values.main.gitea.helmRepoUrl }}
  gitea.chartVersion: {{ .Values.main.gitea.chartVersion }}
  analytics.enabled: {{ .Values.main.analytics.enabled | quote }}

  # gitops.sourceNamespace: GitOpsDefaultCatalogSourceNamespace
  # gitops.installApprovalPlan: GitOpsDefaultApprovalPlan
  # gitops.ManualSync: GitOpsDefaultManualSync
  # gitops.name: GitOpsDefaultPackageName
