apiVersion: v1
kind: ConfigMap
metadata:
  name: patterns-operator-config
  namespace: {{ .Values.main.patternsOperator.subscriptionNamespace }}
data:
  gitops.catalogSource: {{ .Values.main.gitops.operatorSource }}
  gitops.channel: {{ .Values.main.gitops.channel }}
  gitea.chartName: {{ .Values.main.gitea.chartName }}
  gitea.helmRepoUrl: {{ .Values.main.gitea.helmRepoUrl }}
  gitea.chartVersion: {{ .Values.main.gitea.chartVersion }}
  analytics.enabled: {{ .Values.main.analytics.enabled | quote }}
  {{- if .Values.main.gitops.additionalArgoAdmins }}
  gitops.additionalArgoAdmins: {{ .Values.main.gitops.additionalArgoAdmins }}
  {{- end }}
  {{- if .Values.main.gitops.argoRBAC }}
  gitops.argoRBAC: |
{{ .Values.main.gitops.argoRBAC | indent 4 }}
  {{- end }}

  # gitops.sourceNamespace: GitOpsDefaultCatalogSourceNamespace
  # gitops.installApprovalPlan: GitOpsDefaultApprovalPlan
  # gitops.ManualSync: GitOpsDefaultManualSync
  # gitops.name: GitOpsDefaultPackageName
